#!/bin/sh
# gen-games.sh — the cartridge manifest, generated. Scans games/*.c for `const Game game_X` and
# writes gen/games.gen.h: an extern for each cartridge plus the roster the shell shows. `menu` is the
# shell itself, not a cartridge, so it's left out. Drop a .c in games/, rebuild, and it appears on the
# shelf — no array to hand-edit. This is the emulator reading its ROM folder, done at build time: the
# games/ folder IS the library, and building is the cartridge going in. build.sh runs this first.
set -e
cd "$(dirname "$0")/.."
mkdir -p gen
OUT=gen/games.gen.h
tmp="$OUT.tmp"
{
  echo "// AUTO-GENERATED by tools/gen-games.sh from games/*.c — do not edit, do not commit."
  echo "// The games/ folder is the cartridge library; this manifest is regenerated on every build."
  echo "#ifndef GAMES_GEN_H"
  echo "#define GAMES_GEN_H"
  echo "#include \"game.h\""
  echo
  syms=""
  for f in $(ls games/*.c | sort); do
    s=$(grep -oE 'const Game game_[A-Za-z0-9_]+' "$f" | head -1 | sed 's/const Game //')
    [ -z "$s" ] && continue          # a .c with no cartridge in it (a shared helper) is skipped
    [ "$s" = "game_menu" ] && continue
    echo "extern const Game $s;"
    syms="$syms $s"
  done
  echo
  echo "static const Game *const GEN_GAMES[] = {"
  for s in $syms; do echo "    &$s,"; done
  echo "};"
  echo "enum { GEN_NGAMES = (int)(sizeof GEN_GAMES / sizeof GEN_GAMES[0]) };"
  echo "#endif"
} > "$tmp"
mv "$tmp" "$OUT"
