#!/bin/sh
# gen-games.sh — the cartridge manifest, generated. Scans games/*.c for `const Game game_X` and
# writes gen/games.gen.h: an extern for each cartridge plus the roster the shell shows. `menu` is the
# shell itself, not a cartridge, so it's left out. Drop a .c in games/, rebuild, and it appears on the
# shelf — no array to hand-edit. This is the emulator reading its ROM folder, done at build time: the
# games/ folder IS the library, and building is the cartridge going in. build.sh runs this first.
set -e
cd "$(dirname "$0")/.."
mkdir -p gen
OUT=gen/games.gen.h
tmp="$OUT.tmp"
obj=$(mktemp -d "${TMPDIR:-/tmp}/gen-games.XXXXXX")
trap 'rm -rf "$obj"' EXIT
# measure games/x.c -> its own text+data bytes on stdout, or nothing if it can't be measured.
measure() {
  ${CC:-cc} -std=c11 -Os -Igen -Isrc -c "$1" -o "$obj/c.o" 2>/dev/null || return 0
  size "$obj/c.o" 2>/dev/null | awk 'NR == 2 && $1 + $2 > 0 { print $1 + $2 }'
}
{
  echo "// AUTO-GENERATED by tools/gen-games.sh from games/*.c — do not edit, do not commit."
  echo "// The games/ folder is the cartridge library; this manifest is regenerated on every build."
  echo "#ifndef GAMES_GEN_H"
  echo "#define GAMES_GEN_H"
  echo "#include \"game.h\""
  echo
  syms=""; files=""
  for f in $(ls games/*.c | sort); do
    s=$(grep -oE 'const Game game_[A-Za-z0-9_]+' "$f" | head -1 | sed 's/const Game //')
    [ -z "$s" ] && continue          # a .c with no cartridge in it (a shared helper) is skipped
    [ "$s" = "game_menu" ] && continue
    echo "extern const Game $s;"
    syms="$syms $s"; files="$files $f"
  done
  echo
  echo "static const Game *const GEN_GAMES[] = {"
  for s in $syms; do echo "    &$s,"; done
  echo "};"
  echo "enum { GEN_NGAMES = (int)(sizeof GEN_GAMES / sizeof GEN_GAMES[0]) };"
  echo
  # Each cartridge's own compiled size, same order as GEN_GAMES (menu_populate indexes both with the
  # same i). Measured by compiling that one .c on its own with the host compiler at -Os and summing
  # the text and data columns of `size` on the object — the cartridge's own code and constants, none
  # of the engine it links against. Berkeley-format `size` (GNU binutils, llvm-size, and the Xcode
  # one all print it by default) is the portable question; `size -m` is Mach-O only. A cartridge
  # that can't be measured (no `size` on PATH, or the lone .c won't compile) gets 0, which game.h
  # defines as "unknown" — and says so on stderr, once per cartridge, instead of silently.
  echo "static const long GEN_BYTES[] = {"
  for f in $files; do
    n=$(measure "$f")
    [ "$n" -gt 0 ] 2>/dev/null || { echo "gen-games: could not measure '$f' — its shelf label shows no size" >&2; n=0; }
    echo "    $n,"
  done
  echo "};"
  echo "#endif"
} > "$tmp"
mv "$tmp" "$OUT"
