#!/usr/bin/env python3
"""jukebox_build — bake arrangement JSON into games/jukebox_songs.h.

Same bargain as song.py: the thinking (arranging) happens upstream, and what ships is the
flattened table the tracker plays. Each arrangement is one JSON file in games/jukebox_arr/:

    { "title": "...", "composer": "...", "album": "classics"|"originals",
      "rps": 8, "rows": 256,
      "tracks": [ { "role":"lead", "instr":0, "notes": [[midi, rows], ...] }, ... ] }

An event may carry a third element, [pitch, rows, 1], to ACCENT that note — it plays at the
tracker's loud velocity instead of the soft default (the byte gets bit 7 set). Absent = normal.
Nothing here marks accents yet; the twelve classics play flat until an arranger's ear says where
the downbeats are.

A track's notes are run-length events [pitch, duration-in-rows], played back to back from
row 0; pitch 0 is a rest and bakes to the tracker's note-off byte (255), so a sustaining
instrument actually lets go. Only the first row of an event carries a byte; the rows after
it hold (0). Channel index = track order; the LAST channel is SFX and is never written, so an
arrangement may use up to NCHAN-1 tracks. Order on the shelf = sorted by album then filename.
An arrangement with fewer tracks than that simply leaves the rest of the grid silent — the
twelve classics here were written for five and still are.

    tools/jukebox_build.py            # reads games/jukebox_arr/*.json -> games/jukebox_songs.h
"""
import json, os, sys, glob

NCHAN = 17
HERE = os.path.dirname(os.path.abspath(__file__))
ARRDIR = os.path.join(HERE, '..', 'games', 'jukebox_arr')
OUT = os.path.join(HERE, '..', 'games', 'jukebox_songs.h')
ALBUMS = ['classics', 'originals']   # index = ALBUM_CLASSICS / ALBUM_ORIGINALS


def flatten(a):
    rows = int(a['rows'])
    grid = [[0] * NCHAN for _ in range(rows)]
    for ch, tr in enumerate(a['tracks'][:NCHAN - 1]):   # last channel reserved for SFX
        r = 0
        for ev in tr['notes']:                          # [pitch, duration, accent?] runs, cursor walk
            p, d = int(ev[0]), int(ev[1])
            accent = len(ev) > 2 and int(ev[2])
            if r >= rows:
                break                                   # an overrunning track just gets cut
            if 21 <= p <= 108:
                grid[r][ch] = p | 0x80 if accent else p   # bit 7 = loud; the tracker splits it back
            elif p == 0:
                grid[r][ch] = 255                       # a rest is a note-off, not a hold
            r += d
    instr = [0] * NCHAN
    for ch, tr in enumerate(a['tracks'][:NCHAN - 1]):
        instr[ch] = int(tr['instr']) & 7
    return rows, grid, instr


def main():
    files = sorted(glob.glob(os.path.join(ARRDIR, '*.json')))
    songs = []
    for f in files:
        with open(f) as fh:
            a = json.load(fh)
        album = ALBUMS.index(a.get('album', 'classics')) if a.get('album') in ALBUMS else 0
        rows, grid, instr = flatten(a)
        voices = len(a['tracks'][:NCHAN - 1])   # how many are actually written — the meter lights these
        songs.append((a['title'], a['composer'], int(a['rps']), rows, instr, grid, album, voices))
    # classics first, then originals; stable within an album (filename order)
    order = sorted(range(len(songs)), key=lambda i: (songs[i][6], i))

    L = []
    L.append('// Generated by tools/jukebox_build.py from games/jukebox_arr/*.json — do not edit.')
    L.append('// A JukeTrack is a flattened tracker table plus its label. The cartridge just looks up.')
    L.append('#ifndef JUKEBOX_SONGS_H')
    L.append('#define JUKEBOX_SONGS_H')
    L.append('#include <stdint.h>')
    L.append('#include "core.h"')
    L.append('enum { ALBUM_CLASSICS, ALBUM_ORIGINALS, ALBUM_N };')
    L.append('typedef struct { const char *title, *composer; const uint8_t *data;')
    L.append('                 uint16_t rows; uint8_t rps; uint8_t instr[NCHAN]; uint8_t album; uint8_t voices; } JukeTrack;')
    for oi, i in enumerate(order):
        title, comp, rps, rows, instr, grid, album, voices = songs[i]
        L.append(f'static const uint8_t JUKE_D{oi}[{rows}][NCHAN] = {{')
        for r in range(rows):
            L.append('  {' + ','.join(str(x) for x in grid[r]) + '},')
        L.append('};')
    L.append(f'#define JUKE_N {len(order)}')
    L.append('static const JukeTrack JUKE[JUKE_N] = {')
    for oi, i in enumerate(order):
        title, comp, rps, rows, instr, grid, album, voices = songs[i]
        t = title.replace('"', '\\"'); c = comp.replace('"', '\\"')
        alb = 'ALBUM_ORIGINALS' if album == 1 else 'ALBUM_CLASSICS'
        L.append(f'  {{ "{t}", "{c}", &JUKE_D{oi}[0][0], {rows}, {rps}, '
                 f'{{{",".join(str(x) for x in instr)}}}, {alb}, {voices} }},')
    L.append('};')
    L.append('#endif')
    with open(OUT, 'w') as fh:
        fh.write('\n'.join(L) + '\n')
    print(f'{OUT}: {len(order)} tracks')


if __name__ == '__main__':
    main()
