// obj2mesh — .obj → a const mesh baked into the binary. Runs at build time, never ships in the game.
//
// Why bake it into the binary instead of reading the file at runtime: no loader, no
// file format, no I/O, no error handling. const data lives in __TEXT, which already
// has a page sitting there empty. Zero runtime cost.
//
// Flat shading only needs the face normal, so vn in the .obj is always ignored and
// normals are always computed from geometry — as a side effect, this lets any tool's
// obj output work, whether or not it bothers writing vn.
//
//   cc -O2 -o obj2mesh tools/obj2mesh.c -lm
//   ./obj2mesh oga.obj oga > src/mesh_oga.h
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define MAXV 8192
#define MAXT 16384

static double vx[MAXV], vy[MAXV], vz[MAXV];
static int ta[MAXT], tb[MAXT], tc[MAXT], tm[MAXT];
static int nv, nt;

// usemtl name → palette ramp, assigned by order of first appearance. The name itself
// carries no meaning here — material N gets ramp N.
static char mtl[64][64];
static int nmtl, cur_mtl;

static int mtl_index(const char *name) {
    for (int i = 0; i < nmtl; i++) if (!strcmp(mtl[i], name)) return i;
    if (nmtl < 64) { snprintf(mtl[nmtl], 64, "%s", name); return nmtl++; }
    return 0;
}

int main(int argc, char **argv) {
    if (argc < 3) { fprintf(stderr, "usage: obj2mesh <in.obj> <name> [shades per material=8]\n"); return 1; }
    const char *name = argv[2];
    int shades = argc > 3 ? atoi(argv[3]) : 8;

    FILE *f = fopen(argv[1], "r");
    if (!f) { fprintf(stderr, "obj2mesh: can't open %s\n", argv[1]); return 1; }

    char line[1024];
    while (fgets(line, sizeof line, f)) {
        if (!strncmp(line, "v ", 2)) {
            if (nv >= MAXV) { fprintf(stderr, "obj2mesh: more than %d vertices\n", MAXV); return 1; }
            sscanf(line + 2, "%lf %lf %lf", &vx[nv], &vy[nv], &vz[nv]); nv++;
        } else if (!strncmp(line, "usemtl ", 7)) {
            char m[64]; sscanf(line + 7, "%63s", m); cur_mtl = mtl_index(m);
        } else if (!strncmp(line, "f ", 2)) {
            // Accepts "f a b c", "f a/b c/d ...", "f a//b ...", and fan-triangulates n-gons
            int idx[64], n = 0;
            char *p = line + 2;
            while (*p && n < 64) {
                while (*p == ' ' || *p == '\t') p++;
                if (*p < '0' || *p > '9') { if (*p == '-') {} else break; }
                int v = atoi(p);
                if (v < 0) v = nv + v; else v -= 1;      // obj is 1-based; negative indices are relative
                idx[n++] = v;
                while (*p && *p != ' ' && *p != '\t') p++;
            }
            for (int i = 1; i + 1 < n; i++) {
                if (nt >= MAXT) { fprintf(stderr, "obj2mesh: more than %d triangles\n", MAXT); return 1; }
                ta[nt] = idx[0]; tb[nt] = idx[i]; tc[nt] = idx[i + 1]; tm[nt] = cur_mtl; nt++;
            }
        }
    }
    fclose(f);
    if (!nv || !nt) { fprintf(stderr, "obj2mesh: no geometry in %s\n", argv[1]); return 1; }

    // Center and scale to ±0.5 units (= ±(1<<15)). The model's own size doesn't matter — placement is the engine's job.
    double lo[3] = { 1e30, 1e30, 1e30 }, hi[3] = { -1e30, -1e30, -1e30 };
    for (int i = 0; i < nv; i++) {
        double v[3] = { vx[i], vy[i], vz[i] };
        for (int k = 0; k < 3; k++) { if (v[k] < lo[k]) lo[k] = v[k]; if (v[k] > hi[k]) hi[k] = v[k]; }
    }
    double ext = 0;
    for (int k = 0; k < 3; k++) if (hi[k] - lo[k] > ext) ext = hi[k] - lo[k];
    if (ext <= 0) ext = 1;
    double s = 65536.0 / ext;   // longest edge → 1.0 unit

    printf("// generated by obj2mesh from %s. Don't hand-edit — change the model and rebuild.\n", argv[1]);
    printf("// %d vertices / %d triangles / %d materials\n", nv, nt, nmtl ? nmtl : 1);
    printf("static const V3 %s_v[%d] = {\n", name, nv);
    for (int i = 0; i < nv; i++) {
        long X = lrint((vx[i] - (lo[0] + hi[0]) / 2) * s);
        long Y = lrint((vy[i] - (lo[1] + hi[1]) / 2) * s);
        long Z = lrint((vz[i] - (lo[2] + hi[2]) / 2) * s);
        printf("  {%ld,%ld,%ld},%s", X, Y, Z, (i % 4 == 3) ? "\n" : "");
    }
    printf("\n};\nstatic const Tri %s_t[%d] = {\n", name, nt);
    for (int i = 0; i < nt; i++) {
        // Face normal = (b-a) × (c-a), normalized to Q15. This is the only real work this tool does.
        double ux = vx[tb[i]] - vx[ta[i]], uy = vy[tb[i]] - vy[ta[i]], uz = vz[tb[i]] - vz[ta[i]];
        double wx = vx[tc[i]] - vx[ta[i]], wy = vy[tc[i]] - vy[ta[i]], wz = vz[tc[i]] - vz[ta[i]];
        double nx = uy * wz - uz * wy, ny = uz * wx - ux * wz, nz = ux * wy - uy * wx;
        double L = sqrt(nx * nx + ny * ny + nz * nz);
        if (L < 1e-12) L = 1;                       // degenerate face: normal comes out 0, lighting picks the darkest step
        int NX = (int)lrint(nx / L * 32767), NY = (int)lrint(ny / L * 32767), NZ = (int)lrint(nz / L * 32767);
        printf("  {%d,%d,%d,%d,%d,%d,%d},\n", ta[i], tb[i], tc[i], 8 + tm[i] * shades, NX, NY, NZ);
    }
    printf("};\nconst Mesh g_%s = { %s_v, %d, %s_t, %d };\n", name, name, nv, name, nt);

    fprintf(stderr, "obj2mesh: %s → %d vertices %d triangles, %d bytes of model data\n",
            argv[1], nv, nt, nv * 12 + nt * 14);
    return 0;
}
